function door_handles = doors()
    % DOORS Creates static platform screen doors
    
    hold on;
    door_handles = struct();
    
    % Door parameters
    door_width = 1.2;
    door_height = 2.5;
    door_depth = 0.05;
    platform_edge = 1.5; % Distance from track center
    
    % Three door pairs along platform
    door_positions_y = [-12, 0, 12];
    
    for pair = 1:length(door_positions_y)
        % Left door (facing platform)
        [x_left, y_left] = meshgrid(...
            [0, door_depth], ...
            [0, door_width]);
        z_left = [0, 0; door_height, door_height];
        
        door_handles.(['left_door_', num2str(pair)]) = surf(...
            x_left - platform_edge, ...
            y_left + door_positions_y(pair) - door_width/2, ...
            z_left, ...
            'FaceColor', [0.9 0.9 0.95], ...
            'EdgeColor', [0.5 0.5 0.5], ...
            'LineWidth', 1);
        
        % Right door (facing train)
        door_handles.(['right_door_', num2str(pair)]) = surf(...
            x_left + platform_edge - door_depth, ...
            y_left + door_positions_y(pair) - door_width/2, ...
            z_left, ...
            'FaceColor', [0.9 0.9 0.95], ...
            'EdgeColor', [0.5 0.5 0.5], ...
            'LineWidth', 1);
        
        % Door frame - FIXED FIELD NAMES
        frame_width = 0.1;
        
        % Vertical frames
        for side_idx = 1:2
            side_val = [-1, 1]; % Use array for side values
            side = side_val(side_idx);
            
            x_frame = (-platform_edge + (side>0)*(2*platform_edge - door_depth)) * ones(2);
            y_frame = [door_positions_y(pair) - door_width/2, door_positions_y(pair) + door_width/2];
            z_frame = [0, door_height; 0, door_height];
            
            % Create proper field name
            if side < 0
                field_name = ['frame_', num2str(pair), '_left'];
            else
                field_name = ['frame_', num2str(pair), '_right'];
            end
            
            door_handles.(field_name) = surf(...
                x_frame + (side>0)*frame_width/2 - (side<0)*frame_width/2, ...
                [y_frame; y_frame], ...
                z_frame, ...
                'FaceColor', [0.4 0.4 0.4], ...
                'EdgeColor', 'none');
        end
        
        % Top frame
        x_top = [-platform_edge, -platform_edge + door_depth, ...
                 platform_edge - door_depth, platform_edge];
        y_top = [door_positions_y(pair) - door_width/2, door_positions_y(pair) + door_width/2];
        [x_top_grid, y_top_grid] = meshgrid(x_top, y_top);
        z_top = door_height * ones(size(x_top_grid));
        
        door_handles.(['top_frame_', num2str(pair)]) = surf(...
            x_top_grid, y_top_grid, z_top, ...
            'FaceColor', [0.4 0.4 0.4], ...
            'EdgeColor', 'none');
        
        % Floor marking (yellow safety line)
        marking_length = door_width + 0.4;
        marking_width = 0.05;
        
        y_marking = linspace(door_positions_y(pair) - marking_length/2, ...
                            door_positions_y(pair) + marking_length/2, 10);
        x_marking = -platform_edge + door_depth + 0.2;
        
        for i = 1:length(y_marking)-1
            x_patch = [x_marking, x_marking + marking_width, ...
                      x_marking + marking_width, x_marking];
            y_patch = [y_marking(i), y_marking(i+1), ...
                      y_marking(i+1), y_marking(i)];
            z_patch = [0, 0, 0, 0];
            
            patch(x_patch, y_patch, z_patch, ...
                [1 1 0], ...
                'EdgeColor', 'none', ...
                'FaceAlpha', 0.7);
        end
    end
    
    % Overhead door indicator lights (red/green)
    for pair = 1:length(door_positions_y)
        [x_light, y_light, z_light] = sphere(8);
        
        % Red light (off)
        door_handles.(['light_red_', num2str(pair)]) = surf(...
            x_light*0.08 - platform_edge + door_depth/2, ...
            y_light*0.08 + door_positions_y(pair), ...
            z_light*0.08 + door_height + 0.2, ...
            'FaceColor', [0.3 0 0], ...
            'EdgeColor', 'none');
        
        % Green light (off)
        door_handles.(['light_green_', num2str(pair)]) = surf(...
            x_light*0.08 + platform_edge - door_depth/2, ...
            y_light*0.08 + door_positions_y(pair), ...
            z_light*0.08 + door_height + 0.2, ...
            'FaceColor', [0 0.2 0], ...
            'EdgeColor', 'none');
    end
    
    door_handles.all = findobj(gca, 'Type', 'surface');
    axis equal;
end